on:
  push:
    branches:
      - main
    paths:
      - 'go.mod'
      - '**.go'

  pull_request:
    paths:
      - 'go.mod'
      - '**.go'

jobs:
  test:
    name: Test on Go v${{ matrix.go-version }} at ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run unit tests
        run: go test -race -covermode=atomic -coverprofile="profile.cov" ./...

      - name: Send Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: go-${{ matrix.os }}-${{ matrix.go-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
